---
- name: Configure httpd server
  hosts: all
  remote_user: ansible
  become: true
  tasks:
    - name: Install httpd package
      yum:
        name: httpd
        state: latest
    - name: Create content
      copy:
        content: "Welcome to tunetolinux.com"
        dest: /var/www/html/index.html
        force: yes
    - name: Start and enable service
      service:
        name: httpd
        state: started
        enabled: true
